kind: Deployment
apiVersion: apps/v1
metadata:
  name: dip-event-listener
  labels:
    app: dip-event-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dip-event-listener
  template:
    metadata:
      labels:
        app: dip-event-listener
    spec:
      containers:
      - name: dip-event-listener
        image: <!--image-->
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: pg-connection
        - secretRef:
            name: chain
        env:
        - name: AMQP_MODE
          value: core
        - name: AMQP_HOST
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: AMQP_PORT
          value: "$(RABBITMQ_SERVICE_PORT_AMQP)"
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_USERNAME
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_PASSWORD
