apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    app: migrate
spec:
  # backoffLimit: 0
  template:
    metadata:
      name: migrate
      labels:
        app: migrate
    spec:
      containers:
      - name: dip-contracts
        image: <!--image-->
        env:
        - name: NETWORK
          value: dip_rpc
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_SECRET_KEY
        - name: AWS_ENDPOINT
          value: "http://$(MINIO_SERVICE_HOST):$(MINIO_SERVICE_PORT)"
        - name: AMQP_MODE
          value: core
        - name: AMQP_HOST
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: AMQP_PORT
          value: "$(RABBITMQ_SERVICE_PORT_AMQP)"
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_USERNAME
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_PASSWORD
      # restartPolicy: Never
      restartPolicy: OnFailure
