apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    app: migrate
spec:
  # backoffLimit: 0
  template:
    metadata:
      name: migrate
      labels:
        app: migrate
    spec:
      containers:
      - name: dip-contracts
        image: <!--image-->
        env:
        - name: NETWORK
          value: dip_rpc
        - name: MESSAGE_BROKER
          value: "amqp://platform:guest@$(RABBITMQ_SERVICE_HOST):$(RABBITMQ_SERVICE_PORT_AMQP)/trusted"
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_SECRET_KEY
        - name: AWS_ENDPOINT
          value: "http://$(MINIO_SERVICE_HOST):$(MINIO_SERVICE_PORT)"
      # restartPolicy: Never
      restartPolicy: OnFailure
