image: node:9.9.0


pipelines:
  default:
    - step:
        name: Test
        script:
          - npm install
          - npm run test

  custom:
    deploy-staging:
      - step:
          name: Test
          script:
            - npm install
            - npm run test
      - step:
          name: Deploy to STAGING
          deployment: staging
          trigger: manual
          image: google/cloud-sdk:latest
          services:
            - docker
          caches:
            - docker
          script:
            - gcloud -v
            - docker version

definitions:
  services:
    docker:
      memory: 2048
