image: node:9.9.0


pipelines:
  default:
    - step:
        name: Test
        script:
          - npm install
          - npm run test

  custom:
    deploy-staging:
      - step:
          name: Deploy to STAGING
          deployment: staging
          image: gloud
          services:
            - docker
          caches:
            - docker
          script:
            - gcloud -v
            - docker version
            - node -v
            - npm -v

definitions:
  services:
    gcloud:
      image: google/cloud-sdk:latest
    docker:
      memory: 2048
