image: node:9.9.0


pipelines:
  default:
  - step:
      name: Test
      script:
      - npm install
      - npm run test

  custom:
    deploy-staging:
    - step:
        name: Deploy to STAGING
        deployment: staging
        services:
          - docker
        caches:
          - docker
        script:
          - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          - chmod +x ./kubectl
          - sudo mv ./kubectl /usr/local/bin/kubectl
          - SDK_VERSION=216.0.0
          - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
          - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
          - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
          - /tmp/google-cloud-sdk/install.sh -q
          - source /tmp/google-cloud-sdk/path.bash.inc
          - gcloud -v
          - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
          - gcloud auth activate-service-account --key-file gcloud-api-key.json
          - gcloud config set project $GCLOUD_PROJECT
          - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone=$GCLOUD_ZONE --project $GCLOUD_PROJECT
          - gcloud auth configure-docker --quiet
          - node -v
          - npm -v
          - kubectl config get-contexts
          - kubectl version
          - export ENVIRONMENT=production
          - npm install
          - ./node_modules/.bin/lerna bootstrap
          - NODE_ENV=production ./bin/run deploy

definitions:
  services:
    docker:
      memory: 2048

