image: node:9.9.0


pipelines:
  default:
  - step:
      name: Test
      script:
      - npm install
      - npm run test

  custom:
    deploy-staging:
    - step:
        name: Test
        script:
        - export ENVIRONMENT=production
        - npm install
        - npm run test
    - step:
        name: Deploy to STAGING
        deployment: staging
        trigger: manual
        image: google/cloud-sdk:latest
        services:
          - docker
        caches:
          - docker
        script:
          - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
          - gcloud auth activate-service-account --key-file gcloud-api-key.json
          - gcloud config set project $GCLOUD_PROJECT
          - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone=$GCLOUD_ZONE --project $GCLOUD_PROJECT
          - gcloud auth configure-docker --quiet
          - kubectl config get-contexts

definitions:
  services:
    docker:
      memory: 2048

