apiVersion: apps/v1
kind: Deployment
metadata:
  name: dip-platform-deployment
  labels:
    app: dip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: test
        ports:
        - containerPort: 8080
