apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-persistent-volume
  labels:
    type: local
    app: rabbitmq
    tier: infrastructure
spec:
  storageClassName: rabbitmq-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: '/podMount/rabbitmq'
    type: DirectoryOrCreate
