kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 15672
  selector:
    app: rabbitmq
