apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-volume-claim
  labels:
    app: rabbitmq
    tier: infrastructure
spec:
  storageClassName: rabbitmq-storage
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
