kind: Service
apiVersion: v1
metadata:
  name: license-manager
  labels:
    app: license-manager
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 4001
    targetPort: 3000
  selector:
    app: license-manager
