kind: Deployment
apiVersion: apps/v1
metadata:
  name: license-manager
  labels:
    app: license-manager
    tier: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-manager
  template:
    metadata:
      labels:
        app: license-manager
    spec:
      containers:
        - name: license-manager
          image: <!--image-->
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: pg-connection
            - secretRef:
                name: jwt
          env:
          - name: AMQP_MODE
            value: license
          - name: AMQP_HOST
            value: "$(RABBITMQ_SERVICE_HOST)"
          - name: AMQP_PORT
            value: "$(RABBITMQ_SERVICE_PORT_AMQP)"
          - name: RABBIT_API_HOST
            value: "$(RABBITMQ_MANAGEMENT_SERVICE_HOST)"
          - name: RABBIT_API_PORT
            value: "$(RABBITMQ_MANAGEMENT_SERVICE_PORT_HTTP)"
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: AMQP_PLATFORM_USERNAME
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: AMQP_PLATFORM_PASSWORD
          - name: RABBIT_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: AMQP_ADMIN_USERNAME
          - name: RABBIT_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: AMQP_ADMIN_PASSWORD

