kind: Deployment
apiVersion: apps/v1
metadata:
  name: dip-ethereum-client
  labels:
    app: dip-ethereum-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dip-ethereum-client
  template:
    metadata:
      labels:
        app: dip-ethereum-client
    spec:
      containers:
      - name: dip-policy-storage
        image: gcr.io/speedy-atom-216213/dip-ethereum-client:0.0.1
        ports:
        - containerPort: 3000
        env:
        - name: MESSAGE_BROKER
          value: "amqp:$(RABBITMQ_SERVICE_HOST):$(RABBITMQ_SERVICE_PORT_AMQP)"
