apiVersion: v1
kind: Secret
metadata:
  name: fdd-temp
type: Opaque
data:
  FDD_MNEMONIC: d2F5IHdlYiBjaGFwdGVyIHNhdGlzZnkgc29saWQgZnV0dXJlIGF2b2lkIHB1c2ggaW5zYW5lIHZpYWJsZSBkaXp6eSBjb25kdWN0IGZvcmsgZmFudGFzeSBhc3RobWE=
  FDD_ACCOUNT: MHg1RTM5MTcyMWM4ZjYxQzRGMUU1OEE3NGQxYTJmMDI0MjhlOTIyQ0RF
  FDD_HTTP_PROVIDER: YUhSMGNITTZMeTlsZEdndGNtbHVhMlZpZVM1aGJHTm9aVzE1WVhCcExtbHZMMnB6YjI1eWNHTXZMWGxFWnpkM2JXZEhkelZNWkhOUU5IQTBhM2w0VWxsMVJIcERhMWgwYjBrPQ==
