kind: Deployment
apiVersion: apps/v1
metadata:
  name: policy-storage
  labels:
    app: policy-storage
    tier: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-storage
  template:
    metadata:
      labels:
        app: policy-storage
        role: rabbitmq-core-client
    spec:
      containers:
        - name: policy-storage
          image: <!--image-->
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: pg-connection
          env:
          - name: AMQP_MODE
            value: core
          - name: AMQP_HOST
            value: "$(RABBITMQ_SERVICE_HOST)"
          - name: AMQP_PORT
            value: "$(RABBITMQ_SERVICE_PORT_AMQP)"
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: AMQP_PLATFORM_USERNAME
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: AMQP_PLATFORM_PASSWORD
          livenessProbe:
            httpGet:
              path: /live
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
