kind: Deployment
apiVersion: apps/v1
metadata:
  name: dip-pdf-generator
  labels:
    app: dip-pdf-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dip-pdf-generator
  template:
    metadata:
      labels:
        app: dip-pdf-generator
    spec:
      containers:
      - name: dip-pdf-generator
        image: <!--image-->
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: pg-connection
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_SECRET_KEY
        - name: AWS_ENDPOINT
          value: "http://$(MINIO_SERVICE_HOST):$(MINIO_SERVICE_PORT)"
        - name: AMQP_MODE
          value: core
        - name: AMQP_HOST
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: AMQP_PORT
          value: "$(RABBITMQ_SERVICE_PORT_AMQP)"
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_USERNAME
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_PASSWORD
