version: '3'

services:

  Ganache:
    container_name: ${NODE_ENV}_ganache
    image: ${GANACHE_IMAGE}
    command: --mnemonic '${GANACHE_MNEMONIC}' --networkId ${GANACHE_NETWORK_ID} --db /data
    restart: always
    volumes:
      - ./volumes/${NODE_ENV}_ganache:/data
    ports:
      - "127.0.0.1:${GANACHE_PORT}:8545"

  EthereumBridge:
    container_name: ${NODE_ENV}_ethereum_bridge
    image: ${ETHEREUM_BRIDGE_IMAGE}
    command: -H ${NODE_ENV}_ganache:${GANACHE_PORT} -a 9 --dev
    restart: always
    links:
      - "Ganache:${NODE_ENV}_ganache"
    depends_on:
      - Ganache
