apiVersion: v1
kind: Service
metadata:
  name: dip-policy-storage-service
  labels:
    app: dip-policy-storage
spec:
  type: NodePort
  ports:
  - port: 3010
    targetPort: 3010
    nodePort: 30080
    protocol: TCP
  selector:
    app: dip-policy-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dip-policy-storage-deployment
  labels:
    app: dip-policy-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dip-policy-storage
  template:
    metadata:
      labels:
        app: dip-policy-storage
    spec:
      containers:
      - name: dip-policy-storage
        image: dip_policy_storage:0.4.0
        ports:
        - containerPort: 3010
        env:
        - name: MESSAGE_BROKER
          value: "amqp:$(RABBITMQ_SERVICE_HOST):$(RABBITMQ_SERVICE_PORT_AMQP)"
