kind: Deployment
apiVersion: apps/v1
metadata:
  name: ethereum-client
  labels:
    app: ethereum-client
    tier: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-client
  template:
    metadata:
      labels:
        app: ethereum-client
    spec:
      containers:
      - name: ethereum-client
        image: <!--image-->
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: pg-connection
        env:
        - name: AMQP_MODE
          value: core
        - name: AMQP_HOST
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: AMQP_PORT
          value: "$(RABBITMQ_SERVICE_PORT_AMQP)"
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_USERNAME
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: AMQP_PLATFORM_PASSWORD
