apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gif-contracts-volume-claim
  labels:
    app: gif-contracts
spec:
  storageClassName: gif-contracts-storage
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
