kind: Deployment
apiVersion: apps/v1
metadata:
  name: fddui
  labels:
    app: fddui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fddui
  template:
    metadata:
      labels:
        app: fddui
    spec:
      containers:
      - name: fddui
        image: <!--image-->
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: STRIPE_PKEY
          valueFrom:
            secretKeyRef:
              name: payment
              key: STRIPE_PUBLIC_KEY
        volumeMounts:
        - name: fdd-ssl
          mountPath: /etc/ssl
          readOnly: true
    volumes:
      - name: fdd-ssl
        secret: fdd-ssl
