apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio
    tier: infrastructure
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
